### ISSUE TITLE
软件安装报错

### ISSUE THREAD

**Issue by yaosl** [hongdavid94/scAI-SNP#1]
ImportError: cannot import name 'center' from 'scAI_SNP.helper' (/raid8/yaosl/06.biosoft/miniconda3/lib/python3.10/site-packages/scAI_SNP/helper.py)

**Comment by hongdavid94** [comment]
Hi Yao, could you try again by re-installing the package at https://github.com/hormoz-lab/scAI-SNP? The center function should no longer be part of the script
